add error message

diff --git a/.github/workflows/adp-ci.yml b/.github/workflows/adp-ci.yml
--- a/.github/workflows/adp-ci.yml
+++ b/.github/workflows/adp-ci.yml
@@ -18,6 +18,8 @@ jobs:
           yq_deny_expression='.branches.'"${base_branch}"'.deny[] | select("'"${head_branch}"'" == .)'
           yq_allow_expression='.branches.'"${base_branch}"'.allow[] | select("'"${head_branch}"'" == .)'
 
+          echo "::set-output name=head_branch::$head_branch"
+          echo "::set-output name=base_branch::$base_branch"
           echo "::set-output name=yq_deny_expression::$yq_deny_expression"
           echo "::set-output name=yq_allow_expression::$yq_allow_expression"
 
@@ -37,11 +39,11 @@ jobs:
 
       - name: Evaluate Rule
         run: |
-          deny_result=${{ steps.getDenyRules.outputs.result }}
-          allow_result=${{ steps.getAllowRules.outputs.result }}
+          deny_result="${{ steps.getDenyRules.outputs.result }}"
+          allow_result="${{ steps.getAllowRules.outputs.result }}"
 
-          [ ! -z "$deny_result" ] && exit 1
-          [ -z "$allow_result" ] && exit 1
+          [ ! -z "$deny_result" ] && echo "::error title=Merging is not allowed::Merging to branch ${{ steps.getBranchName.outputs.base_branch }} from branch ${{ steps.getBranchName.outputs.head_branch }} is explicitly denied" && exit 1
+          [ -z "$allow_result" ] && echo "::error title=Merging is not allowed::Merging to branch ${{ steps.getBranchName.outputs.base_branch }} from branch ${{ steps.getBranchName.outputs.head_branch }} is not allowed" && exit 1
 
   # adf-validation:
   #   runs-on: ubuntu-20.04
