add error message

diff --git a/.github/workflows/adp-ci.yml b/.github/workflows/adp-ci.yml
--- a/.github/workflows/adp-ci.yml
+++ b/.github/workflows/adp-ci.yml
@@ -7,34 +7,43 @@ jobs:
   branch-validation:
     runs-on: ubuntu-20.04
     steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
       - name: Get head and base branch name
         id: getBranchName
         run: |
           head_branch=${GITHUB_HEAD_REF##*/}
           base_branch=${GITHUB_BASE_REF##*/}
+          yq_deny_expression='.branches.'"${base_branch}"'.deny[] | select("'"${head_branch}"'" == .)'
+          yq_allow_expression='.branches.'"${base_branch}"'.allow[] | select("'"${head_branch}"'" == .)'
 
-          echo "::set-output name=base_branch::$base_branch"
           echo "::set-output name=head_branch::$head_branch"
+          echo "::set-output name=base_branch::$base_branch"
+          echo "::set-output name=yq_deny_expression::$yq_deny_expression"
+          echo "::set-output name=yq_allow_expression::$yq_allow_expression"
+
+          yq --help
 
       - name: Get Deny Rules
         id: getDenyRules
         uses: mikefarah/yq@v4.16.2
         with:
-          cmd: yq eval '.branches.'"${steps.getBranchName.outputs.base_branch}"'.deny[] | select("'"${steps.getBranchName.outputs.head_branch}"'" == .)' .github/branch-rules.yml
-
-      - name: List Deny Rule
-        run: |
-          echo ${steps.getDenyRules.outputs.result}
+          cmd: yq eval '${{ steps.getBranchName.outputs.yq_deny_expression }}' .github/branch-rules.yml
 
       - name: Get Allow Rules
         id: getAllowRules
         uses: mikefarah/yq@v4.16.2
         with:
-          cmd: yq eval '.branches.'"${steps.getBranchName.outputs.base_branch}"'.allow[] | select("'"${steps.getBranchName.outputs.head_branch}"'" == .)' .github/branch-rules.yml
+          cmd: yq eval '${{ steps.getBranchName.outputs.yq_allow_expression }}' .github/branch-rules.yml
 
-      - name: List Allow Rule
+      - name: Evaluate Rule
         run: |
-          echo ${steps.getAllowRules.outputs.result}
+          deny_result="${{ steps.getDenyRules.outputs.result }}"
+          allow_result="${{ steps.getAllowRules.outputs.result }}"
+
+          [ ! -z "$deny_result" ] && echo "::error title=Merging is not allowed::Merging to branch ${{ steps.getBranchName.outputs.base_branch }} from branch ${{ steps.getBranchName.outputs.head_branch }} is explicitly denied" && exit 1
+          [ -z "$allow_result" ] && echo "::error title=Merging is not allowed::Merging to branch ${{ steps.getBranchName.outputs.base_branch }} from branch ${{ steps.getBranchName.outputs.head_branch }} is not allowed" && exit 1
 
   # adf-validation:
   #   runs-on: ubuntu-20.04
